"""Research report generator: a dated, self-contained markdown verdict."""

from __future__ import annotations

import datetime as dt

from newsom2028 import config


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def _cents(x: float) -> str:
    return f"{100 * x:.1f}¢"


def write(record: dict) -> str:
    as_of = record["as_of"]
    s = record["summary"]
    lanes = record["lanes"]
    nom = record["contracts"]["nominee"]
    pres = record["contracts"]["president"]

    lines: list[str] = []
    add = lines.append

    add(f"# Newsom 2028 valuation — {as_of}")
    add("")
    add("Auto-generated by `newsom2028 run`. Methodology: `docs/METHODOLOGY.md`; "
        "assumptions and sensitivity: `docs/ASSUMPTIONS.md`; what this analysis "
        "cannot tell you: `docs/LIMITATIONS.md`.")
    add("")
    add("## Verdict")
    add("")
    add("| Contract | Market price | Model fair value (median) | 80% credible interval | Verdict |")
    add("|---|---|---|---|---|")
    add(f"| Democratic nomination | {_cents(nom['market_price'])} | "
        f"{_cents(nom['fair_median'])} | {_cents(nom['fair_p10'])} – {_cents(nom['fair_p90'])} | "
        f"**{nom['verdict']}** |")
    add(f"| Presidency | {_cents(pres['market_price'])} | {_cents(pres['fair_median'])} | "
        f"{_cents(pres['fair_p10'])} – {_cents(pres['fair_p90'])} | **{pres['verdict']}** |")
    add("")
    add(f"Decision rule (pre-registered): BUY requires median fair value ≥ "
        f"{record['gate']['edge_ratio']}× price **and** the "
        f"{record['gate']['gate_percentile']}th-percentile fair value to clear price "
        f"plus carry (risk-free {_pct(record['risk_free'])}) plus "
        f"{_cents(record['gate']['round_trip_cost'])} round-trip cost. One of two → "
        "SPECULATIVE VALUE. Gate results:")
    add("")
    add(f"- Nomination: {nom['gate_detail']}")
    add(f"- Presidency: {pres['gate_detail']}")
    add("")
    add("## Decomposition")
    add("")
    add("`P(president) = P(nominee) × P(wins general | nominee)`")
    add("")
    add("| Leg | Market-implied | Model median | 80% CI |")
    add("|---|---|---|---|")
    market_cond = record["prices"]["president"] / record["prices"]["nominee"]
    add(f"| P(nominee) | {_pct(record['prices']['nominee'])} | "
        f"{_pct(s['nominee']['median'])} | {_pct(s['nominee']['p10'])} – {_pct(s['nominee']['p90'])} |")
    add(f"| P(general \\| nominee) | {_pct(market_cond)} | {_pct(s['conditional']['median'])} | "
        f"{_pct(s['conditional']['p10'])} – {_pct(s['conditional']['p90'])} |")
    add(f"| P(president) | {_pct(record['prices']['president'])} | "
        f"{_pct(s['president']['median'])} | {_pct(s['president']['p10'])} – {_pct(s['president']['p90'])} |")
    add("")
    add("## Model lanes (independent views before ensembling)")
    add("")
    add("| Lane | Leg | Median | Basis |")
    add("|---|---|---|---|")
    br = lanes["base_rate"]
    add(f"| Historical base rate | P(nominee) | {_pct(br['median'])} | "
        f"{br['k']}/{br['n']} top-2-standing candidates won open nominations, 1972–2024 |")
    an = lanes["analog"]
    add(f"| Historical analogs | P(nominee) | {_pct(an['median'])} | similarity-weighted win "
        f"rate {_pct(an['weighted_win_rate'])}, effective n = {an['effective_n']:.1f} |")
    ms = lanes["market_structure"]
    add(f"| Market structure | P(nominee) | {_pct(ms['median'])} | price "
        f"{_cents(ms['market_price'])} with favorite-longshot correction |")
    fu = lanes["fundamentals"]
    add(f"| Fundamentals | P(general \\| nom) | {_pct(fu['median'])} | open-seat out-party base "
        f"rate {_pct(fu['raw_base_rate'])} shrunk to {_pct(fu['shrunk_base_rate'])}, "
        "minus Newsom-specific adjustment |")
    mi = lanes["market_implied_conditional"]
    add(f"| Market-implied conditional | P(general \\| nom) | {_pct(mi['median'])} | "
        "presidency price / nominee price |")
    add("")
    add("### Closest historical analogs")
    add("")
    add("| Cycle | Candidate | Similarity | Won nomination |")
    add("|---|---|---|---|")
    for row in an["top_analogs"][:10]:
        add(f"| {row['cycle']} {row['party']} | {row['candidate']} | "
            f"{row['weight']:.2f} | {'✔' if row['won_nomination'] else '✘'} |")
    add("")
    add("## Cross-candidate conditional anomaly")
    add("")
    add("Market-implied P(wins general | nominated) — presidency price ÷ nominee price. "
        "Spreads across candidates that fundamentals can't explain are the main "
        "relative-value signal:")
    add("")
    add("| Candidate | Nominee price | Presidency price | Implied conditional |")
    add("|---|---|---|---|")
    for row in record["implied_conditionals"]:
        add(f"| {row['candidate']} | {_cents(row['nominee_price'])} | "
            f"{_cents(row['president_price'])} | {_pct(row['implied_conditional'])} |")
    add("")
    add("## Exit scenarios (speculative)")
    add("")
    add("Mark-to-market exits assuming the nominee-contract price converges a fraction "
        "κ toward model fair value by each milestone. These are assumptions about "
        "other traders, not forecasts:")
    add("")
    add("| Milestone | Date | κ | Assumed exit | Return | Annualized | Beats carry? |")
    add("|---|---|---|---|---|---|---|")
    for row in record["scenarios"]:
        add(f"| {row['milestone']} | {row['date']} | {row['convergence_kappa']} | "
            f"{_cents(row['assumed_exit_price'])} | {row['return_pct']}% | "
            f"{row['annualized_pct']}% | {'yes' if row['beats_carry'] else 'no'} |")
    add("")
    add("## Position sizing")
    add("")
    add(f"- Nomination contract Kelly fraction: **{_pct(nom['kelly_fraction'])}** of bankroll "
        f"(half-Kelly {_pct(nom['kelly_fraction'] / 2)} recommended given model uncertainty)")
    add(f"- Presidency contract Kelly fraction: **{_pct(pres['kelly_fraction'])}**")
    add("")
    add("## Honesty notes")
    add("")
    add("- This is a single unrepeatable event; the 2028 outcome can neither validate nor "
        "refute this model. Only the method is testable (see backtests in METHODOLOGY).")
    add("- Favorite-longshot bias — the best-documented prediction-market inefficiency — "
        "pushes *against* the undervaluation thesis at these price levels and is priced "
        "into the market-structure lane.")
    add("- The historical panel is small (~18 open contests). Every interval above is wide "
        "because the evidence is genuinely thin, not because the model is broken.")
    add("")

    text = "\n".join(lines)
    config.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    (config.REPORTS_DIR / f"{as_of}-verdict.md").write_text(text)
    (config.REPORTS_DIR / "latest.md").write_text(text)
    return text
